In [6]:
import numpy as np
import time

# --- 1. NumPy Fundamentals (Creation, Indexing & Slicing) ---
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print("1D Array Indexing (Element at 3):", arr_1d[3])
print("1D Array Slicing (Elements 2 to 6):", arr_1d[2:7])

# --- 2. Mathematical & Axis-Wise Operations ---
# Slide Requirement: Axis-wise and Statistical operations
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Matrix:\n", matrix)

# Axis 0 = Columns, Axis 1 = Rows
print("Sum of Columns (Axis 0):", np.sum(matrix, axis=0))
print("Sum of Rows (Axis 1):", np.sum(matrix, axis=1))

# --- 3. Statistical Operations ---
# Slide Requirement: Statistical operations on datasets
print("\n--- Statistical Summary ---")
print(f"Mean (Average): {np.mean(arr_1d)}")
print(f"Median: {np.median(arr_1d)}")
print(f"Standard Deviation: {np.std(arr_1d)}")
print(f"Variance: {np.var(arr_1d)}")

# --- 4. Reshaping & Broadcasting ---
# Slide Requirement: Reshaping and broadcasting techniques
reshaped = arr_1d.reshape(3, 3)
print("\nReshaped to 3x3 Matrix:\n", reshaped)
# Broadcasting (Adding 100 to every element)
print("Broadcasting (Array + 100):\n", arr_1d + 100)

# --- 5. Save/Load and Performance ---
np.save('syntecxhub_task1.npy', arr_1d)

# Speed Comparison
size = 1000000
p_list = list(range(size))
n_arr = np.arange(size)

start = time.time()
sum(p_list)
p_time = time.time() - start

start = time.time()
np.sum(n_arr)
n_time = time.time() - start

print(f"\nPython List Time: {p_time:.5f}s")
print(f"NumPy Array Time: {n_time:.5f}s")
print(f"Performance: NumPy is {p_time/n_time:.2f}x faster!")

1D Array Indexing (Element at 3): 40
1D Array Slicing (Elements 2 to 6): [30 40 50 60 70]

2D Matrix:
 [[1 2 3]
 [4 5 6]]
Sum of Columns (Axis 0): [5 7 9]
Sum of Rows (Axis 1): [ 6 15]

--- Statistical Summary ---
Mean (Average): 50.0
Median: 50.0
Standard Deviation: 25.81988897471611
Variance: 666.6666666666666

Reshaped to 3x3 Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Broadcasting (Array + 100):
 [110 120 130 140 150 160 170 180 190]

Python List Time: 0.01041s
NumPy Array Time: 0.00108s
Performance: NumPy is 9.60x faster!
